package com.myheart.caiwu.entity;

import java.util.Date;

public class CoreProductGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.request_source
     *
     * @mbggenerated
     */
    private String requestSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.period
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.asset_level
     *
     * @mbggenerated
     */
    private String assetLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.pay_source
     *
     * @mbggenerated
     */
    private String paySource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_product_group.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.id
     *
     * @return the value of core_product_group.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.id
     *
     * @param id the value for core_product_group.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.request_source
     *
     * @return the value of core_product_group.request_source
     *
     * @mbggenerated
     */
    public String getRequestSource() {
        return requestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.request_source
     *
     * @param requestSource the value for core_product_group.request_source
     *
     * @mbggenerated
     */
    public void setRequestSource(String requestSource) {
        this.requestSource = requestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.period
     *
     * @return the value of core_product_group.period
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.period
     *
     * @param period the value for core_product_group.period
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.asset_level
     *
     * @return the value of core_product_group.asset_level
     *
     * @mbggenerated
     */
    public String getAssetLevel() {
        return assetLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.asset_level
     *
     * @param assetLevel the value for core_product_group.asset_level
     *
     * @mbggenerated
     */
    public void setAssetLevel(String assetLevel) {
        this.assetLevel = assetLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.pay_source
     *
     * @return the value of core_product_group.pay_source
     *
     * @mbggenerated
     */
    public String getPaySource() {
        return paySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.pay_source
     *
     * @param paySource the value for core_product_group.pay_source
     *
     * @mbggenerated
     */
    public void setPaySource(String paySource) {
        this.paySource = paySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.create_time
     *
     * @return the value of core_product_group.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.create_time
     *
     * @param createTime the value for core_product_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_product_group.update_time
     *
     * @return the value of core_product_group.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_product_group.update_time
     *
     * @param updateTime the value for core_product_group.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}