package com.myheart.caiwu.mappers;

import com.myheart.caiwu.entity.CoreProductGroup;
import org.springframework.stereotype.Repository;

@Repository
public interface CoreProductGroupMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int insert(CoreProductGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int insertSelective(CoreProductGroup record);

    CoreProductGroup queryByPrimaryKey(Long id);

}