package com.myheart.caiwu.mappers;

import com.myheart.caiwu.entity.CoreProductGroup;
import com.myheart.caiwu.entity.CoreProductGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CoreProductGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int countByExample(CoreProductGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int deleteByExample(CoreProductGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int insert(CoreProductGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int insertSelective(CoreProductGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    List<CoreProductGroup> selectByExample(CoreProductGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    CoreProductGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreProductGroup record, @Param("example") CoreProductGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreProductGroup record, @Param("example") CoreProductGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoreProductGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_product_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoreProductGroup record);
}